# Generated by Django 4.2.21 on 2025-06-11 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL标识"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
            options={
                "verbose_name": "图书分类",
                "verbose_name_plural": "图书分类",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="书名")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL标识"
                    ),
                ),
                ("author", models.CharField(max_length=100, verbose_name="作者")),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="book_covers/", verbose_name="封面图片"
                    ),
                ),
                ("published_date", models.DateField(verbose_name="出版日期")),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "已发布"), ("draft", "草稿")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="bookapp.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "图书",
                "verbose_name_plural": "图书",
                "ordering": ["-created_at"],
            },
        ),
    ]
